version: "3.7"

services:
  frontend:
    image: mystapp
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./Streamlit_Frontend:/app
        - ./storage:/storage

  backend:
    image: backend
    ports:
      - 8000:8000
    volumes:
      - ./FastAPI_Backend:/app
      - ./storage:/storage
